### ISSUE TITLE
knit PDF

### ISSUE THREAD

**Issue by pamaneec** [pamaneec/Homeownership-and-integration#2]
@AaronGullickson 

It shows this and does not knit. 

processing file: SOC513_Paper.Rmd
Error in parse_block(g[-1], g[1], params.src) : 
  duplicate label 'generation'
Calls: <Anonymous> ... process_file -> split_file -> lapply -> FUN -> parse_block
Execution halted

**Comment by AaronGullickson** [comment]
I think you have two code chunks with the same name. Or some other kind of duplication of the label "generation".

**Comment by pamaneec** [comment]
@AaronGullickson 
I update that "generation" but I ran into another problem. Somehow it doesn't run polr model when I knit. 

For model 7-9 I change them to glm but they don't work at all.

Thanks for your help.

**Comment by AaronGullickson** [comment]
@pamaneec I see two problems, although I dont know if this is up to date because I dont see models 7-9. First to run polr, you need to include `library(MASS)`  in your setup code chunk. Second, you are calling `data=imputation` on all of your models. There is no `imputation`. Your data is `pew`. Works fine for me when I fix those things.

**Comment by pamaneec** [comment]
I load library(MASS)
For imputation, I have imputation in my analysis which works fine. However, when I copy the chuck to the paper it might not be there. What do I need to do?

**Comment by AaronGullickson** [comment]
@pamaneec If you used multiple imputation then you need to pool the results using the code we discussed in the section on missing values. You can't just put in as the dataset because there are five different complete datasets. It should look something like:

```r
model.mi <- pool(with(imputations, glm(-some formula-, family=binomial)))
summary(model.mi)
```

Alternatively, you could just forget the imputation and do listwise deletion.

**Comment by pamaneec** [comment]
Aaron, 

I commit and push everything. However, I still encounter errors and cannot knit the file. Is it possible to meet you today so that all assignments are completely submitted?

Thank you very much. 

Best,
Pamanee

**Comment by AaronGullickson** [comment]
@pamaneec 

The main problem was the use of `fig.align=TRUE` in the R code chunks. That works for HTML but not for PDF. I corrected those issues and also a few other syntax things in commit 9f2a21755c4172ffa8836bc02221fbd3fcf58b9c. I have made a few comments there about changes that I made. It knits fine now.

**Comment by pamaneec** [comment]
Thank you very much Aaron. I submit the pdf on Canvas. 

I hope to spend my summer and really read through your text and slides. There are many research design you put into content that I couldn’t keep up in the class while we also need to deal with coding and math issues. 

Thanks again for your kind help. I help you don’t mind if I still ask you more questions. 

Have a great summer. 

Best,
Pamanee
